name: TEST CI

on: 
  push:
    branches:
      - develop
      - prae
  pull_request:
    branches:
      - main

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"